### ISSUE TITLE
这里是不是还有单独的工程

### ISSUE THREAD

**Issue by leaf-pay** [ad-dev-kit/gae-das#1]
/**
     * 发送HTTP请求报告自己binlog位置
     * @param binlog
     * @param pos
     * @return true表示自己可成为master, fales表示不可成为master
     */
    private boolean sendReport(String binlog, long pos) {
        BeatMessage msg = BeatMessage.Builder.buildReport(binlog, pos);

        HttpPost post = new HttpPost("http://" + peerHost + ":" + peerPort);

**Comment by wanghongfei** [comment]
没有单独工程

**Comment by leaf-pay** [comment]
这个端口是？


das:
  mysql:
    server-id: 1

  ha:
    port: 10000
    peer-host: 127.0.0.1
    peer-port: 10001

**Comment by leaf-pay** [comment]
[10:30:26] [nioEventLoopGroup-3-1] WARN  o.fh.gae.das.ha.CoordinationService - Connect to 127.0.0.1:10001 [/127.0.0.1] failed: Connection refused: connect

**Comment by wanghongfei** [comment]
这个意思是连接另外一个DAS实例，可以启动两个das, 相互发心跳，一个挂了另一个自动接手

**Comment by leaf-pay** [comment]
tks
