### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by leaf-pay** [ad-dev-kit/gae-das#2]
DemoTableListener  
private FileSender store;  ----->    private DasSender store;

可以考虑一下兼容
 EXT_WRITE_ROWS,
    /**
     * Describes updated rows (within a single table).
     * Used in case of RBR (5.1.18+).
     */
    EXT_UPDATE_ROWS,
    /**
     * Describes deleted rows (within a single table).
     * Used in case of RBR (5.1.18+).
     */
    EXT_DELETE_ROWS,

**Comment by wanghongfei** [comment]
嗯，这个说对，是应该改一下
